name: Deploy Front End

on:
    push:
        branches: [ main ]
        paths: 
        - 'frontend/**'


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: azure/login@v1
      with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Upload to blob storage
      uses: azure/CLI@v1
      with:
        inlineScript: |
            az storage blob upload-batch --account-name azureresumeacgsl --auth-mode key --overwrite true -d '$web' -s frontend/ 
    - name: Purge CDN endpoint
      uses: azure/CLI@v1
      with:
        inlineScript: |
           az cdn endpoint purge --content-paths  "/*" --profile-name "azureresumeacgsl" --name "azureresumeacgsl" --resource-group "getresumecountersl"

  # Azure logout
    - name: logout
      run: |
            az logout
      if: always()